name: flutter_tapers
description: Tapers that ensure you can use types from the Flutter SDK with Chest.
version: 0.1.0-0
repository: https://github.com/chestdb/flutter_tapers

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  chest: ^0.1.0-0
  flutter:
    sdk: flutter
