name: flutter_tapers
version: 0.1.2
description: Tapers that ensure you can use types from the Flutter SDK with Chest.
repository: https://github.com/chestdb/flutter_tapers

environment:
  flutter: '>=3.0.0'
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  chest: ^0.1.1
  flutter:
    sdk: flutter
